version: '3.8'

volumes:
  data:


services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8001:8000
#    environment:
#      - DATABASE_NAME=postgres_user
#      - TEST_DATABASE_NAME=postgres_password
    depends_on:
      postgres:
        condition: service_healthy
      testdb:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  testdb:
    image: postgres:latest
    ports:
      - "5435:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped